[[redirects]]
  from = "https://www.discord.melee.uk"
  to = "https://www.discord.com/invite/MHWfdKC"
  status = 301
  force = true

[[redirects]]
  from = "https://www.bham.melee.uk"
  to = "https://www.discord.gg/Vm2hZhn"
  status = 301
  force = true
