backend:
  name: github
  repo: spirrit/meleeuk
  branch: master
  api_root: https://api.github.com
  site_domain: api.netlify.com
  # site_domain: melee.uk
  base_url: https://api.netlify.com
  auth_endpoint: auth
  cms_label_prefix: cms/
publish_mode: editorial_workflow
media_folder: "src/cms/uploads"
public_folder: "cms/uploads"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "blog.njk",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Tags", name: "tags", default: "blog", widget: "hidden" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "home"
    label: "Home page"
    folder: "src"
    create: false
    slug: "index"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "index2.njk",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "links"
    label: "Links pages"
    folder: "src/links"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "links.njk",
        }
      - { label: "Tags", name: "tags", default: "links", widget: "hidden" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "settings"
    label: "Settings"
    files:
      - label: "Navigation"
        file: "src/_data/navigation.json"
        name: "navigation"
        fields:
          - label: "Nav link"
            name: navitems
            widget: list
            fields:
              - { label: Label, name: label, widget: string }
              - { label: Path, name: path, widget: string }
  - name: "recurring_event"
    label: "Recurring Events (weeklies)"
    folder: "src/events/weeklies"
    create: true
    identifier_field: name
    extension: "json"
    fields:
      - {
          label: "Frequency",
          name: "frequency",
          widget: "select",
          options: ["Weekly", "Fortnightly", "Monthly"],
          default: "Weekly",
        }
      - { label: "Occurs on", name: "occurs_on", widget: "string" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - {
          label: "Address",
          name: "address",
          widget: "string",
          default: "",
          required: false,
        }
      - {
          label: "Link",
          name: "link",
          widget: "string",
          default: "",
          required: false,
        }
      - {
          label: "Stream",
          name: "stream",
          widget: "string",
          default: "",
          required: false,
        }
      - {
          label: "Discord",
          name: "discord",
          widget: "string",
          default: "",
          required: false,
        }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          default: "",
          required: false,
        }
  - name: "one_off_event"
    label: "One-off Events"
    folder: "src/events/tournaments"
    create: true
    identifier_field: name
    slug: "{{slug}}"
    extension: "json"
    fields:
      - {
          label: "Level",
          name: "level",
          widget: "select",
          options: ["Regional", "National", "International"],
          default: "Regional",
        }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          date_format: "DD.MM.YYYY", # e.g. 24.12.2021
          time_format: "HH:mm", # e.g. 21:07
        }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Address", name: "address", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Discord", name: "discord", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
